### ISSUE TITLE
Is this method learnable?

### ISSUE THREAD

**Issue by XuyangBai** [abenbihi/elf#1]
Hi, Thanks for your sharing ! I wonder is your method learnable? Is . there any ways to finetune the pretrained model on my own dataset?

**Comment by HencyChen** [comment]
> 
> 
> Hi, Thanks for your sharing ! I wonder is your method learnable? Is . there any ways to finetune the pretrained model on my own dataset?

Hi, I'm not the author, but I'm familiar to their work. ELF is a non-learning based approach. It totally depend on their proposed saliency generation process to detect keypoint, and need to combined to existing descriptor for feature matching.

**Comment by XuyangBai** [comment]
OK, Thanks a lot.
